profile        = "terraform"                       # In what account will keep terraform.tfstate
bucket         = "dev-me-terraform-state"           # Тот же bucket, что и environments/develop
key            = "eks-access-lab/identity/terraform.tfstate"
region         = "us-east-1"                        # Bucket region (bucket уже существует в us-east-1)
use_lockfile   = true
encrypt        = true
