profile        = "terraform"              # In what account will keep terraform.tfstate
bucket         = "dev-me-terraform-state" # In what bucket will keep terraform.tfstate
key            = "terraform.tfstate"      # Name of key: terraform.tfstate
region         = "us-east-1"              # Bucket region
use_lockfile   = true
encrypt        = true
