apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    # Используем AWS Load Balancer Controller для создания NLB
    alb.ingress.kubernetes.io/scheme: internet-facing              # Для доступа из интернета
    alb.ingress.kubernetes.io/target-type: ip                     # Роутинг на IP подов
    alb.ingress.kubernetes.io/load-balancer-attributes: routing.http2.enabled=true
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'      # Настройка порта
    alb.ingress.kubernetes.io/backend-protocol: HTTP              # Протокол между ALB и подами
    #alb.ingress.kubernetes.io/subnets: subnet-002263b6d3ec26635,subnet-0bb12159fd4d62342  # Список сабнетов для NLB
  labels:
    app: guestbook
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend                                     # Имя сервиса, на который роутится трафик
                port:
                  number: 80                                       # Порт сервиса

